-- CREATE TABLE disneydates (
--     event_id SERIAL PRIMARY KEY,
--     event_date DATE NOT NULL,
--     event_description VARCHAR(2000) NOT NULL,
--     news_type VARCHAR(100) NOT NULL
-- );

INSERT INTO disneydates (event_Date, event_description, news_type)
VALUES ('January 1', 'Fantasyland Autopia opens at Disneyland Park', 'Parks and Resorts'),
('January 1', 'Walt Disney Pictures releases Fantasia 2000 in IMAX', 'Animation'),
('January 2', 'The Worm Turns, a Mickey Mouse short, debuts', 'Animation'),
('January 2', 'Disneys Grand Californian Hotel and Spa at the Disneyland Resort welcomes its first Guests', 'Parks and Resorts'),
('May 21', 'The animated short, Donald Dream Voice, debuts', 'Animation'),
('May 22', 'Rocket Rods, Honey, I Shrunk the Audience, Astro Orbitor and Redd Rocketts Pizza Port open at Disneyland Park', 'Parks and Resorts'),
('May 23', 'Walt Disney incorporates Laugh-O-Gram Films, his first cartoon company in Kansas City', 'Walt Disney'),
('May 23', 'Light Magic debuts at Disneyland Park', 'Parks and Resorts'),
('May 24', 'The Magic Carpets of Aladdin opens at Magic Kingdom Park', 'Parks and Resorts'),
('May 25', 'Walt Disney Pictures releases Pirates of the Caribbean: At Worlds End', 'Studio'),
('May 26', 'Disney-Pixar premieres Cars in Charlotte, NC', 'Pixar Animation'),
('May 27', 'Space Mountain opens at Disneyland Park', 'Parks and Resorts'),
('May 28', 'its a small world opens at Disneyland Park', 'Parks and Resorts'),
('May 29', 'Disney-Pixar releases Up', 'Pixar Animation'),
('May 30', 'Disney-Pixar releases Finding Nemo', 'Pixar Animation'),
('May 31', 'Toy Story Midway Mania opens at Hollywood Studios', 'Parks and Resorts'),
('June 1', 'Typhoon Lagoon opens at the Walt Disney World Resort', 'Parks and Resorts'),
('June 2', 'The Laserphonic Fantasy premieres at the World Showcase Lagoon at Epcot', 'Parks and Resorts'),
('June 3', 'Star Tours: The Adventures Continue opens at Disneyland Park', 'Parks and Resorts'),
('June 4', 'Bengal Barbecue opens at Disneyland Park', 'Parks and Resorts'),
('June 5', 'The Many Adventures of Winnie the Pooh opens at Magic Kingdom Park', 'Parks and Resorts'),
('June 6', 'Submarine Voyage opens at Disneyland Park', 'Parks and Resorts'),
('June 6', 'Walt Disney Pictures releases Herbie Rides Again', 'Studio'),
('June 7', 'The animated series Kim Possible debuts on Disney Channel', 'Disney Channel'),
('June 8', 'The animated short Test Pilot Donald debuts', 'Animation'),
('June 9', 'Donald Duck celebrates his 50th birthday', 'Animation'),
('June 10', 'Pack Mules Through Natures Wonderland opens in Frontierland at Disneyland Park', 'Parks and Resorts'),
('June 11', 'The Main Street Electrical Parade debuts at Magic Kingdom Park', 'Parks and Resorts'),
('June 12', 'Miles the giraffe is the first animal to arrive at Animal Kingdom facilities', 'Parks and Resorts'),
('June 13', 'Carnation Cafe reopens at Disneyland Park', 'Parks and Resorts'),
('June 14', 'Hercules Weekend takes place in Times Square in New York, with a special Electrical Parade and world premiere of the film', 'Animation'),
('June 15', 'Club 33 opens in New Orleans Square at Disneyland Park', 'Parks and Resorts'),
('June 14', 'The Lion King is released', 'Animation')